### PR TITLE
Added config option to specify source folder

### PR DESCRIPTION
**Pull request by spacemanspiff2007**
Added an configuration option to specify the path of the source folder.
This will make aerich work with various folder structures (e.g. ./src/MyPythonModule)
Additionally this will try to import in init and show the user the error message on failure.

### CODE REVIEW

**Comment by spacemanspiff2007** [comment]
This will also fix/prevent e.g. #95

**Comment by spacemanspiff2007** [comment]
@long2ice 
Could you take a look at this? I am currently unable to deploy/use aerich.
With this PR it works fine

**Comment by long2ice** [comment]
Your case maybe point here https://github.com/tortoise/aerich/blob/dev/aerich/cli.py#L297

**Comment by spacemanspiff2007** [comment]
Yes, but with the additional arg I can configure it for both the deployment and local use without having to patch aerich.
If you could merge/review the pr it would be really great!

**Comment by long2ice** [comment]
Maybe put it in `aerich.ini` is better, which is a global config

**Comment by spacemanspiff2007** [comment]
> 
> 
> Maybe put it in `aerich.ini` is better, which is a global config

This pr does both!

**Review by long2ice — APPROVED** [review]

**Comment by spacemanspiff2007** [comment]
@long2ice 
I reformatted the changed files with black, so I hope your ci runs now properly

**Comment by spacemanspiff2007** [comment]
Hmm, still fails. 😞 

I ran ``black -l 100 -t py38 aerich/``.
Can you provide me with a hint how I can fix the failing ci check?

**Comment by spacemanspiff2007** [comment]
@long2ice I think I got it. In the pyproject you specified an older black version.
Now it should run fine! 👍

**Comment by long2ice** [comment]
Thanks!

**Comment by spacemanspiff2007** [comment]
Would you mind making a release so I use the official package for the deployment?

**Pull request merged**
