### PR TITLE
Close Tortoise connections properly

### PR DESCRIPTION
**Pull request by AulonSal**
Addresses issue #120 

Chooses the simplest solution of always running Tortoise.close_connections() in the coro wrapper.

### CODE REVIEW

**Comment by long2ice** [comment]
Hi, this update I tried before but had some problems, you can try some commands in different databases in local

**Comment by AulonSal** [comment]
Tried it with postgresql and there indeed is a problem, what the update is doing is basically what tortoise.run_async does but it's only meant for simple scripts so I went and made an asynccontextmanager-decorator and wrapped the database-touching functions in it and that seems to work but I still want to figure out if it can work at a higher level and why it failed in the coro wrapper.

I made TortoiseCloseConnections a class based decorator/context-manager but if it's never going to be used in a with clause it can be replaced with the following decorator:
```python
def tortoise_connection_cleanup(func):
    @wraps(func)
    async def inner(*args, **kwds):
        try:
            return await func(*args, **kwds)
        finally:
            await Tortoise.close_connections()
    return inner
```

**Comment by AulonSal** [comment]
You could alternatively import run_async from tortoise and define wrapper as:
```python
    def wrapper(*args, **kwargs):
        if f.__name__ != 'cli':
            run_async(f(*args, **kwargs)
        else:
            loop = asyncio.get_event_loop()
            loop.run_until_complete(f(*args, **kwargs))
```

**Comment by long2ice** [comment]
OK, thanks fot that! Just one thing, could you update version and changelog? Which in `pyproject.toml` and `aerich/__init__.py`.

**Review by long2ice — APPROVED** [review]

**Comment by long2ice** [comment]
Thanks!

**Pull request merged**
